config/routes.rb
ConsultingApp::Application.routes.draw do
  root :to => 'pages#index'

  match '/add', :to => 'consultants#new'
  match '/addcareers', :to => 'careers#new'
  match '/addbooks', :to => 'books#new'

  match '/export', :to => 'pages#export_json'
  match '/xml', :to => 'pages#export_xml'
  match '/import', :to => 'pages#import_json'

  resources :consultants
  resources :careers
  resources :books
  resources :consultings
  resources :news
  resources :cautions

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :id, :subject, :author, :publisher, :year, :consultant_id

  belongs_to :consultant

  validates :consultant_id, :presence => true
  validates :subject, :presence => true
end

app/models/career.rb
class Career < ActiveRecord::Base
  attr_accessible :id, :since_date, :until_date, :substance, :consultant_id

  belongs_to :consultant

  validates :consultant_id, :presence => true
  validates :substance, :presence => true
end

app/models/caution.rb
class Caution < ActiveRecord::Base
  belongs_to :consulting

  validates :content, :presence => true
end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
  has_many :careers, :dependent => :destroy
  has_many :books, :dependent => :destroy
  
  validates :name, :presence => true

  after_create :create_photo_path

  private
  def create_photo_path
    unless self.photo
      self.photo = "pic_#{self.id}"
      self.save
    end
  end

end

app/models/consulting.rb
class Consulting < ActiveRecord::Base
  has_many :cautions, :dependent => :destroy
  has_many :news, :dependent => :destroy
  belongs_to :consultant

  validates :topic, :presence => true
  validates :consultant_id, :presence => true
  
  # after_create :create_movie_path

  # private
  # def create_movie_path
  #   unless self.movie
  #     self.movie = "mov_#{self.id}"
  #     self.save
  #   end
  # end
end

app/models/news.rb
class News < ActiveRecord::Base
  validates :link_address, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @consultant_id = params[:consultant_id] unless @consultant_id
    @books = Book.find(:all, :conditions => "consultant_id = '#{@consultant_id}'")
  end

  def create
    @book = Book.new(params[:book])
    @book.save
    redirect_to :action => :new, :consultant_id => @book.consultant_id
  end

  def destroy
    @book = Book.find_by_id(params[:id])
    @book.delete
    redirect_to :action => :new, :consultant_id => @book.consultant_id
  end

end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def new
    @career = Career.new
    @consultant_id = params[:consultant_id] unless @consultant_id
    @careers = Career.find(:all, :conditions => "consultant_id = '#{@consultant_id}'")
  end

  def create
    @career = Career.new(params[:career])
    @career.save
    redirect_to :action => :new, :consultant_id => @career.consultant_id
  end

  def update
    @career = Career.new(params[:id])
    @career.save
    redirect_to :action => :new, :consultant_id => @career.consultant_id
  end

  def destroy
    @career = Career.find_by_id(params[:id])
    @career.delete
    redirect_to :action => :new, :consultant_id => @career.consultant_id
  end

end

app/controllers/cautions_controller.rb
class CautionsController < ApplicationController
  def new
    @caution = Caution.new
    @consulting_id = params[:consulting_id] unless @consulting_id
    @cautions = Caution.find(:all, :conditions => "consulting_id = '#{@consulting_id}'")
  end

  def create
    @caution = Caution.new(params[:caution])
    @caution.save
    redirect_to :action => :new, :consulting_id => @caution.consulting_id
  end

  def update
    @caution = Caution.new(params[:id])
    @caution.save
    redirect_to :action => :new, :consulting_id => @caution.consulting_id
  end

  def destroy
    @caution = Caution.find_by_id(params[:id])
    @caution.delete
    redirect_to :action => :new, :consulting_id => @caution.consulting_id
  end

end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController

  def index
    @consultants = Consultant.all
  end

  def show
    @consultant = Consultant.find_by_id(params[:id])
  end

  def new
    if params[:consultant_id]
      @consultant = Consultant.find_by_id(params[:consultant_id])
    else
      @consultant = Consultant.new
    end
  end

  def create
    @consultant = Consultant.new(params[:consultant])
    
    if @consultant.save
      redirect_to new_career_path(:consultant_id => @consultant.id)
    else
      render 'new'
    end
  end

  def update
    @consultant = Consultant.find_by_id(params[:id])
    
    @consultant.update_attributes(params[:consultant])

    # @consultant.name = params[:consultant][:name]
    # @consultant.department = params[:consultant][:department]
    # @consultant.job = params[:consultant][:job]
    # @consultant.homepage = params[:consultant][:homepage]
    # @consultant.facebook = params[:consultant][:facebook]
    # @consultant.twitter = params[:consultant][:twitter]
    # @consultant.email = params[:consultant][:email]
    # @consultant.phone = params[:consultant][:phone]
    # @consultant.address = params[:consultant][:address]

    if @consultant.save
      redirect_to new_career_path(:consultant_id => @consultant.id)
    else
      render 'new'
    end
  end

  def destroy
    @consultant = Consultant.find_by_id(params[:id])
    @consultant.delete
    redirect_to root_path
  end

end

app/controllers/consultings_controller.rb
class ConsultingsController < ApplicationController
  def new
    if params[:consulting_id]
      @consulting = Consulting.find_by_id(params[:consulting_id])
    else
      @consulting = Consulting.new
    end
    @consultants = Consultant.all
  end

  def create
    @consulting = Consulting.new(params[:consulting])
    @consultants = Consultant.all
    if @consulting.save
      redirect_to new_caution_path(:consulting_id => @consulting.id)
    else
      @consulting = Consulting.new
      render 'new'
    end
  end

  def update
    @consulting = Consulting.find_by_id(params[:id])

    @consulting.update_attributes(params[:consulting])

    # @consulting.topic = params[:consulting][:topic]
    # @consulting.consultant_id = params[:consulting][:consultant_id]
    # @consulting.detail = params[:consulting][:detail]
    # @consulting.movie = params[:consulting][:movie]

    if @consulting.save
      redirect_to new_caution_path(:consulting_id => @consulting.id)
    else
      render 'new'
    end
  end

  def destroy
    @consulting = Consulting.find_by_id(params[:id])
    @consulting.delete
    redirect_to root_path
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
    @news = News.new
    @consulting_id = params[:consulting_id] unless @consulting_id
    @newses = News.find(:all, :conditions => "consulting_id = '#{@consulting_id}'")
  end

  def create
    @news = News.new(params[:news])
    @news.save
    redirect_to :action => :new, :consulting_id => @news.consulting_id
  end

  def update
    @news = News.new(params[:id])
    @news.save
    redirect_to :action => :new, :consulting_id => @news.consulting_id
  end

  def destroy
    @news = News.find_by_id(params[:id])
    @news.delete
    redirect_to :action => :new, :consulting_id => @news.consulting_id
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @consultings = Consulting.all
  end

  def export_json
    @consultings = Consulting.all
    aFile = File.new("consultings.json", "w")
    aFile.write(@consultings.to_json(:include => {:cautions => {}, :news => {}, :consultant => {:include => {:careers => {}, :books => {}}}}))
    aFile.close
    render :json => @consultings.to_json(:include => {:cautions => {}, :news => {}, :consultant => {:include => {:careers => {}, :books => {}}}})
  end

  def import_json
    json = params[:upload]
    puts '======================'
    render :json => json.to_json
  end

  def export_xml
    @consultings = Consulting.all
    render :xml => @consultings.to_xml(:include => {:cautions => {}, :news => {}, :consultant => {:include => {:careers => {}, :books => {}}}})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/cautions_helper.rb
module CautionsHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/consultings_helper.rb
module ConsultingsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/new.html.erb
<h1>Add Books</h1>

<%= form_for(@book) do |f| %>
<div class="field">
  <%= f.label :책제목 %>
  <%= f.text_field :subject %>
</div>
<div class="field">
  <%= f.label :작가 %>
  <%= f.text_field :author %>
</div>
<div class="field">
  <%= f.label :출판사 %>
  <%= f.text_field :publisher %>
</div>
<div class="field">
  <%= f.label :발행년도 %>
  <%= f.text_field :year %>
</div>

<%= f.hidden_field :consultant_id, :value => @consultant_id %>

<div class="actions">
  <%= f.submit "추가", :class => 'button round' %>
</div>

<% end %>


<ul class="">
  <% @books.each do |book| %>
  <li>
    <div>
      <span>책제목 : </span><span><%= book.subject %></span>
    </div>
    <div>
      <span>작가 : </span><span><%= book.author %></span>
    </div>
    <div>
      <span>출판사 : </span><span><%= book.publisher %></span>
    </div>
    <div>
      <span>발행년도 : </span><span><%= book.year %></span>
    </div>
    <%= link_to "삭제", book_path(book.id), :method => :delete, :class => 'button round' %>
  </li>
  <% end %>
</ul>



<%= link_to "완료!!", root_path, :class => 'button round' %>

app/views/careers/new.html.erb
<h1>Add Careers</h1>

<%= form_for(@career) do |f| %>
<div class="field">
  <%= f.text_field :since_date %>
  부터
</div>
<div class="field">
  <%= f.text_field :until_date %>
  까지
</div>
<div class="field">
  <%= f.label :경력내용 %>
  <%= f.text_field :substance %>
</div>

<%= f.hidden_field :consultant_id, :value => @consultant_id %>

<div class="actions">
  <%= f.submit "Add", :class => 'button round' %>
</div>

<% end %>

<ul class="">
  <% @careers.each do |career| %>
  <li>
    <div>
      <span>경력 : </span><span> <%= career.since_date %> ~ <%= career.until_date %></span>
    </div>
    <div>
      <span>경력내용 : </span><span><%= career.substance %></span>
    </div>
    <%= link_to "삭제", career_path(career.id), :method => :delete, :class => 'button round' %>
  </li>
  <% end %>
</ul>

<%= link_to "다음", new_book_path(:consultant_id => @consultant_id), :class => 'button round' %>

app/views/cautions/new.html.erb
<h1>주의할점</h1>

<%= form_for(@caution) do |f| %>
<div class="field">
  <%= f.label :내용 %><br />
  <%= f.text_field :content %>
</div>

<%= f.hidden_field :consulting_id, :value => @consulting_id %>

<div class="actions">
  <%= f.submit "추가", :class => 'button round' %>
</div>

<% end %>


<ul class="">
  <% @cautions.each do |caution| %>
  <li class="">
    <%= caution.content %>
    <%= link_to "삭제", caution_path(caution.id), :method => :delete, :class => 'button round' %>
  </li>
  <% end %>
</ul>

<%= link_to "다음", new_news_path(:consulting_id => @consulting_id), :class => 'button round' %>

app/views/consultants/index.html.erb
<ul class="">
  <% @consultants.each do |c| %>
  <li>
    <div class="profile_basic">
      <div class="profile_basic_name">
	<p><%= c.name %></p>
      </div>
      <div class="profile_basic_department">
	<p><%= c.department %></p>
      </div>
      <div class="profile_basic_job">
	<p><%= c.job %></p>
      </div>
    </div>
    
    <div class="profile_career">
      <div>주요 경력</div>
      <ul class="profile_career_list">
	<% c.careers.each do |career| %>
        <li>
	  <span class="profile_career_list_year">
	    <%= career.since_date %> ~ <%= career.until_date %>
	  </span>
	  <span class="profile_career_list_substance">
	    <%= career.substance %>
	  </span>
	</li>
	<% end %>
      </ul>
    </div>
    
    <div class="profile_book">
      <div>주요 저서</div>
      <ul class="prifile_book_list">
	<% c.books.each do |book| %>
        <li>
	  <span class="profile_boook_list_subject">
	    <%= book.subject %>
	  </span>
	  <span class="profile_boook_list_author">
	    <%= book.author %>
	  </span>
	  <span class="profile_boook_list_publisher">
	    <%= book.publisher %>
	  </span>
	  <span class="profile_boook_list_year">
	    <%= book.year %>
	  </span>
	</li>
	<% end %>
      </ul>
    </div>
    
    <div class="profile_contacts">
      <div>연락하기</div>
      <ul class="profile_contacts_list">
	<li class="profile_contacts_homepage">
	  홈페이지 : <%= c.homepage %>
	</li>
	<li class="profile_contacts_facebook">
	  페이스북 : <%= c.facebook %>
	</li>
	<li class="profile_contacts_twitter">
	  트위터 : <%= c.twitter %>
	</li>
	<li class="profile_contacts_email">
	  이메일 : <%= c.email %>
	</li>
	<li class="profile_contacts_phone">
	  전화번호 : <%= c.phone %>
	</li>
	<li class="profile_contacts_address">
	  주소 : <%= c.address %>
	</li>
      </ul>
    </div>
  </li>

  <%= link_to "수정", new_consultant_path(:consultant_id => c.id), :class => "button round" %>
  <%= link_to "삭제", consultant_path(c.id), :method => :delete, :class => "button round" %>
  <% end %>
</ul>

app/views/consultants/new.html.erb
<h1>Add Consultant</h1>

<%= form_for(@consultant) do |f| %>
<div class="field">
  <%= f.label :이름 %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :소속 %><br />
  <%= f.text_field :department %>
</div>
<div class="field">
  <%= f.label :직업 %><br />
  <%= f.text_field :job %>
</div>
<div class="field">
  <%= f.label :홈페이지 %><br />
  <%= f.text_field :homepage %>
</div>
<div class="field">
  <%= f.label :페이스북 %><br />
  <%= f.text_field :facebook %>
</div>
<div class="field">
  <%= f.label :트위터 %><br />
  <%= f.text_field :twitter %>
</div>
<div class="field">
  <%= f.label :이메일 %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :전화번호 %><br />
  <%= f.text_field :phone %>
</div>
<div class="field">
  <%= f.label :주소 %><br />
  <%= f.text_field :address %>
</div>
<div class="actions">
  <%= f.submit "다음", :consultant_id => @consultant.id, :class => 'button round' %>
</div>

<% end %>

app/views/consultants/show.html.erb
<ul class="">
  <li>
    <div class="profile_basic">
      <div class="profile_basic_name">
	<p><%= @consultant.name %></p>
      </div>
      <div class="profile_basic_department">
	<p><%= @consultant.department %></p>
      </div>
      <div class="profile_basic_job">
	<p><%= @consultant.job %></p>
      </div>
    </div>
    
    <div class="profile_career">
      <div>주요 경력</div>
      <ul class="profile_career_list">
	<% @consultant.careers.each do |career| %>
        <li>
	  <span class="profile_career_list_year">
	    <%= career.since_date %> ~ <%= career.until_date %>
	  </span>
	  <span class="profile_career_list_substance">
	    <%= career.substance %>
	  </span>
	</li>
	<% end %>
      </ul>
    </div>
    
    <div class="profile_book">
      <div>주요 저서</div>
      <ul class="prifile_book_list">
	<% @consultant.books.each do |book| %>
        <li>
	  <span class="profile_boook_list_subject">
	    <%= book.subject %>
	  </span>
	  <span class="profile_boook_list_author">
	    <%= book.author %>
	  </span>
	  <span class="profile_boook_list_publisher">
	    <%= book.publisher %>
	  </span>
	  <span class="profile_boook_list_year">
	    <%= book.year %>
	  </span>
	</li>
	<% end %>
      </ul>
    </div>
    
    <div class="profile_contacts">
      <div>연락하기</div>
      <ul class="profile_contacts_list">
	<li class="profile_contacts_homepage">
	  홈페이지 : <%= @consultant.homepage %>
	</li>
	<li class="profile_contacts_facebook">
	  페이스북 : <%= @consultant.facebook %>
	</li>
	<li class="profile_contacts_twitter">
	  트위터 : <%= @consultant.twitter %>
	</li>
	<li class="profile_contacts_email">
	  이메일 : <%= @consultant.email %>
	</li>
	<li class="profile_contacts_phone">
	  전화번호 : <%= @consultant.phone %>
	</li>
	<li class="profile_contacts_address">
	  주소 : <%= @consultant.address %>
	</li>
      </ul>
    </div>
  </li>

  <%= link_to "수정", new_consultant_path(:consultant_id => @consultant.id), :class => "button round" %>
  <%= link_to "삭제", consultant_path(@consultant.id), :method => :delete, :class => "button round" %>

</ul>

app/views/consultings/new.html.erb
<h1>Add Consulting</h1>

<%= form_for(@consulting) do |f| %>
<div class="field">
  <%= f.label :주제 %><br />
  <%= f.text_field :topic %>
</div>
<div class="field">
  <%= f.label :상담사 %><br />
  <% if @consultants.count > 0 %>
  <% @consultants.each do |consultant| %>
  <%= f.radio_button :consultant_id, consultant.id %> <%= consultant.name %><br />
  <% end %>
  <% else %>
  <p>등록된 상담사가 없습니다. 상담사를 추가해 주세요!!</p>
  <% end %>
</div>
<div class="field">
  <%= f.label :상세 %><br />
  <%= f.text_area :detail %>
</div>
<div class="field">
  <%= f.label :동영상 %><br />
  <%= f.text_field :movie %>
</div>
<div class="actions">
  <%= f.submit "다음", :class => 'button round' %>
</div>
<% end %>

app/views/news/new.html.erb
<h1>기사 링크</h1>

<%= form_for(@news) do |f| %>

<div class="field">
  <%= f.label :링크주소 %>
  <%= f.text_field :link_address, :value => "http://" %>
</div>

<%= f.hidden_field :consulting_id, :value => @consulting_id %>

<div class="actions">
  <%= f.submit "추가", :class => 'button round' %>
</div>

<% end %>

<ul class="">
  <% @newses.each do |n| %>
  <li class="">
    <%= n.link_address %> <%= link_to "삭제", news_path(n.id), :method => :delete, :class => 'button round' %>
  </li>
  <% end %>
</ul>

<%= link_to "완료", root_path, :class => 'button round' %>