config/routes.rb
ConsultingApp::Application.routes.draw do
  root :to => 'pages#index'

  match '/add', :to => 'consultants#new'
  match '/addcareers', :to => 'careers#new'
  match '/addbooks', :to => 'books#new'

  match '/export', :to => 'pages#export_json'
  match '/xml', :to => 'pages#export_xml'
  match '/import', :to => 'pages#import_json'

  resources :consultants
  resources :careers
  resources :books
  resources :consultings
  resources :news
  resources :cautions

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :id, :subject, :author, :publisher, :year, :consultant_id

  belongs_to :consultant

  validates :consultant_id, :presence => true
  validates :subject, :presence => true
end

app/models/career.rb
class Career < ActiveRecord::Base
  attr_accessible :id, :since_date, :until_date, :substance, :consultant_id

  belongs_to :consultant

  validates :consultant_id, :presence => true
  validates :substance, :presence => true
end

app/models/caution.rb
class Caution < ActiveRecord::Base
  belongs_to :consulting

  validates :content, :presence => true
end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
  has_many :careers, :dependent => :destroy
  has_many :books, :dependent => :destroy
  
  validates :name, :presence => true

  after_create :create_photo_path

  private
  def create_photo_path
    unless self.photo
      self.photo = "pic_#{self.id}"
      self.save
    end
  end

end

app/models/consulting.rb
class Consulting < ActiveRecord::Base
  has_many :cautions, :dependent => :destroy
  has_many :news, :dependent => :destroy
  belongs_to :consultant

  validates :topic, :presence => true
  validates :consultant_id, :presence => true
  
  # after_create :create_movie_path

  # private
  # def create_movie_path
  #   unless self.movie
  #     self.movie = "mov_#{self.id}"
  #     self.save
  #   end
  # end
end

app/models/news.rb
class News < ActiveRecord::Base
  validates :link_address, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @consultant_id = params[:consultant_id] unless @consultant_id
    @books = Book.find(:all, :conditions => "consultant_id = '#{@consultant_id}'")
  end

  def create
    @book = Book.new(params[:book])
    @book.save
    redirect_to :action => :new, :consultant_id => @book.consultant_id
  end

  def destroy
    @book = Book.find_by_id(params[:id])
    @book.delete
    redirect_to :action => :new, :consultant_id => @book.consultant_id
  end

end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def new
    @career = Career.new
    @consultant_id = params[:consultant_id] unless @consultant_id
    @careers = Career.find(:all, :conditions => "consultant_id = '#{@consultant_id}'")
  end

  def create
    @career = Career.new(params[:career])
    @career.save
    redirect_to :action => :new, :consultant_id => @career.consultant_id
  end

  def update
    @career = Career.new(params[:id])
    @career.save
    redirect_to :action => :new, :consultant_id => @career.consultant_id
  end

  def destroy
    @career = Career.find_by_id(params[:id])
    @career.delete
    redirect_to :action => :new, :consultant_id => @career.consultant_id
  end

end

app/controllers/cautions_controller.rb
class CautionsController < ApplicationController
  def new
    @caution = Caution.new
    @consulting_id = params[:consulting_id] unless @consulting_id
    @cautions = Caution.find(:all, :conditions => "consulting_id = '#{@consulting_id}'")
  end

  def create
    @caution = Caution.new(params[:caution])
    @caution.save
    redirect_to :action => :new, :consulting_id => @caution.consulting_id
  end

  def update
    @caution = Caution.new(params[:id])
    @caution.save
    redirect_to :action => :new, :consulting_id => @caution.consulting_id
  end

  def destroy
    @caution = Caution.find_by_id(params[:id])
    @caution.delete
    redirect_to :action => :new, :consulting_id => @caution.consulting_id
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
    @news = News.new
    @consulting_id = params[:consulting_id] unless @consulting_id
    @newses = News.find(:all, :conditions => "consulting_id = '#{@consulting_id}'")
  end

  def create
    @news = News.new(params[:news])
    @news.save
    redirect_to :action => :new, :consulting_id => @news.consulting_id
  end

  def update
    @news = News.new(params[:id])
    @news.save
    redirect_to :action => :new, :consulting_id => @news.consulting_id
  end

  def destroy
    @news = News.find_by_id(params[:id])
    @news.delete
    redirect_to :action => :new, :consulting_id => @news.consulting_id
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @consultings = Consulting.all
  end

  def export_json
    @consultings = Consulting.all
    aFile = File.new("consultings.json", "w")
    aFile.write(@consultings.to_json(:include => {:cautions => {}, :news => {}, :consultant => {:include => {:careers => {}, :books => {}}}}))
    aFile.close
    render :json => @consultings.to_json(:include => {:cautions => {}, :news => {}, :consultant => {:include => {:careers => {}, :books => {}}}})
  end

  def import_json
    json = params[:upload]
    puts '======================'
    render :json => json.to_json
  end

  def export_xml
    @consultings = Consulting.all
    render :xml => @consultings.to_xml(:include => {:cautions => {}, :news => {}, :consultant => {:include => {:careers => {}, :books => {}}}})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/cautions_helper.rb
module CautionsHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/consultings_helper.rb
module ConsultingsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <%= link_to "H O M E", root_path, :class => 'round home' %>
    <div class="header-right">
      <nav class="round">
	<ul class="">
	  <li class="">
	    <%= link_to "Export JSON", export_path %>
	  </li>
	  <li class="">
	    <%= link_to "XML", xml_path %>
	  </li>
	</ul>
      </nav>
      <%= link_to "상담사추가!!", new_consultant_path, :class => 'round add' %>
      <%= link_to "컨설팅추가!!", new_consulting_path, :class => 'round add' %>
    </div>
  </div>
  <div class="file-upload">
    
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConsultantManagementApp</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
	<%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Consulting</h1>

<ul class="">
  <% @consultings.each do |c| %>
  <li class="">
    <div class="">
      <%= c.topic %>
    </div>
    <div class="">
      <%= link_to "#{c.consultant.name}", consultant_path(c.consultant_id) %>
    </div>
    
    <div class="">
      <div class="">
        주의할점
      </div>
      <ul class="">
        <% c.cautions.each do |caution| %>
	<li class="">
	  <%= caution.content %> <%= link_to "삭제", caution_path(caution.id), :method => :delete, :class => 'button round' %>
	</li>
	<% end %>	  
      </ul>
    </div>
    
    <div class="">
      <div class="">
        관련 자료 뉴스 링크
      </div>
      <ul class="">
        <% c.news.each do |n| %>
	<li class="">
	  <%= n.link_address %> <%= link_to "삭제", news_path(n.id), :method => :delete, :class => 'button round' %>
	</li>
	<% end %>	  
      </ul>
    </div>
  </li>
  <%= link_to "수정", new_consulting_path(:consulting_id => c.id), :class => 'button round' %>
  <%= link_to "삭제", consulting_path(c.id), :method => :delete, :class => 'button round' %>
  <% end %>
</ul>